version: '3'
services:
  gps:
    environment:
      - CLIENT_REWARDS_BASE_URL=http://rewards:8082/reward
    build:
        context: ./svc/gps/
        dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    
  rewards:
    build:
        context: ./svc/rewards/
        dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    
  users:
    environment:
      - CLIENT_REWARDS_BASE_URL=http://rewards:8082/reward
      - CLIENT_GPS_BASE_URL=http://gps:8081/gps
    build:
        context: ./svc/users/
        dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
    
  

